language: python
python:
- 3.6
install:
- cp contrib/env-sample .env
- pip install -q -r requirements.txt
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_c1b915d11032_key -iv $encrypted_c1b915d11032_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan dokku@pescar.ifto.edu.br >> ~/.ssh/known_hosts
- git remote add deploy https://github.com/smkbarbosa/pescar.git
- git config --global push.default simple
- git push deploy master
