# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sare.questionarios.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default=None, max_length=100, verbose_name=b'endere\xc3\xa7o')),
                ('num_casa', models.CharField(default=0, max_length=4, verbose_name=b'n\xc3\xbamero da casa')),
                ('cep', models.CharField(default=None, max_length=9, verbose_name=b'cep')),
                ('bairro', models.CharField(max_length=100, verbose_name=b'bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name=b'cidade')),
                ('estado', models.CharField(default=b'TO', max_length=2, verbose_name=b'estado')),
                ('nome', models.CharField(max_length=100, verbose_name=b'nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[sare.questionarios.validators.cpf_is_digits, sare.questionarios.validators.cpf_is_valid], verbose_name=b'CPF')),
                ('email', models.EmailField(max_length=254, verbose_name=b'e-mail')),
                ('fone', models.CharField(blank=True, max_length=20, verbose_name=b'telefone')),
                ('sexo', models.CharField(choices=[(b'M', b'Masculino'), (b'F', b'Feminino')], default=None, max_length=1, verbose_name=b'sexo')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Pessoa')),
                ('curso', models.CharField(choices=[(b'1', b'PROEJA - ATENDIMENTO'), (b'2', b'PROEJA - MANUTEN\xc3\x87\xc3\x83O E OPERA\xc3\x87\xc3\x83O DE MICROCOMPUTADORESs'), (b'3', b'TEC. INT. - T\xc3\x89CNICO EM ADMINISTRA\xc3\x87\xc3\x83O'), (b'4', b'TEC. INT. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'5', b'TEC. INT. - T\xc3\x89CNICO EM AGRONEG\xc3\x93CIO'), (b'6', b'TEC. INT. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL '), (b'7', b'TEC. INT. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'8', b'TEC. INT. - T\xc3\x89CNICO EM EVENTOS'), (b'9', b'TEC. INT. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA PARA INTERNET'), (b'10', b'TEC. INT. - T\xc3\x89CNICO EM MECATR\xc3\x94NICA'), (b'11', b'TEC. SUB. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'12', b'TEC. SUB. - T\xc3\x89CNICO EM AUTOMA\xc3\x87\xc3\x83O INDUSTRIAL'), (b'30', b'TEC. SUB. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL'), (b'13', b'TEC. SUB. - T\xc3\x89CNICO EM EDIFICA\xc3\x87\xc3\x95ES'), (b'14', b'TEC. SUB. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'15', b'TEC. SUB. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA'), (b'16', b'TEC. SUB. - T\xc3\x89CNICO EM SECRETARIADO'), (b'17', b'TEC. SUB. - T\xc3\x89CNICO EM SEGURAN\xc3\x87A DO TRABALHO'), (b'18', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA CIVIL'), (b'19', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA EL\xc3\x89TRICA'), (b'20', b'GRADUA\xc3\x87\xc3\x83O - EDUCA\xc3\x87\xc3\x83O F\xc3\x8dSICA'), (b'21', b'GRADUA\xc3\x87\xc3\x83O - F\xc3\x8dSICA'), (b'22', b'GRADUA\xc3\x87\xc3\x83O - LETRAS - L\xc3\x8dNGUA PORTUGUESA'), (b'23', b'GRADUA\xc3\x87\xc3\x83O - MATEM\xc3\x81TICA'), (b'24', b'GRADUA\xc3\x87\xc3\x83O - AGRONEG\xc3\x93CIO'), (b'25', b'GRADUA\xc3\x87\xc3\x83O - CONSTRU\xc3\x87\xc3\x83O DE EDIF\xc3\x8dCIOS'), (b'26', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O DE TURISMO'), (b'27', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O P\xc3\x9aBLICA'), (b'28', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS EL\xc3\x89TRICOS'), (b'29', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS PARA INTERNET')], default=None, max_length=50, verbose_name=b'curso')),
                ('sem_mod_ano', models.CharField(default=None, max_length=10, verbose_name=b'Semestre/M\xc3\xb3dulo/Ano')),
                ('matricula', models.CharField(default=None, max_length=15, verbose_name=b'matr\xc3\xadcula')),
                ('campus', models.CharField(default=b'PALMAS', max_length=30, verbose_name=b'campus')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
            bases=('core.pessoa',),
        ),
    ]
