# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sare.questionarios.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(default=None, max_length=100, verbose_name='endereço')),
                ('num_casa', models.CharField(default=0, max_length=4, verbose_name='número da casa')),
                ('cep', models.CharField(default=None, max_length=9, verbose_name='cep')),
                ('bairro', models.CharField(max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='cidade')),
                ('estado', models.CharField(default='TO', max_length=2, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'endereço',
                'verbose_name_plural': 'endereços',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[sare.questionarios.validators.cpf_is_digits, sare.questionarios.validators.cpf_is_valid], verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('fone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=None, max_length=1, verbose_name='sexo')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Pessoa')),
                ('curso', models.CharField(choices=[('1', 'PROEJA - ATENDIMENTO'), ('2', 'PROEJA - MANUTENÇÃO E OPERAÇÃO DE MICROCOMPUTADORESs'), ('3', 'TEC. INT. - TÉCNICO EM ADMINISTRAÇÃO'), ('4', 'TEC. INT. - TÉCNICO EM AGRIMENSURA'), ('5', 'TEC. INT. - TÉCNICO EM AGRONEGÓCIO'), ('6', 'TEC. INT. - TÉCNICO EM CONTROLE AMBIENTAL '), ('7', 'TEC. INT. - TÉCNICO EM ELETROTÉCNICA'), ('8', 'TEC. INT. - TÉCNICO EM EVENTOS'), ('9', 'TEC. INT. - TÉCNICO EM INFORMÁTICA PARA INTERNET'), ('10', 'TEC. INT. - TÉCNICO EM MECATRÔNICA'), ('11', 'TEC. SUB. - TÉCNICO EM AGRIMENSURA'), ('12', 'TEC. SUB. - TÉCNICO EM AUTOMAÇÃO INDUSTRIAL'), ('30', 'TEC. SUB. - TÉCNICO EM CONTROLE AMBIENTAL'), ('13', 'TEC. SUB. - TÉCNICO EM EDIFICAÇÕES'), ('14', 'TEC. SUB. - TÉCNICO EM ELETROTÉCNICA'), ('15', 'TEC. SUB. - TÉCNICO EM INFORMÁTICA'), ('16', 'TEC. SUB. - TÉCNICO EM SECRETARIADO'), ('17', 'TEC. SUB. - TÉCNICO EM SEGURANÇA DO TRABALHO'), ('18', 'GRADUAÇÃO - ENGENHARIA CIVIL'), ('19', 'GRADUAÇÃO - ENGENHARIA ELÉTRICA'), ('20', 'GRADUAÇÃO - EDUCAÇÃO FÍSICA'), ('21', 'GRADUAÇÃO - FÍSICA'), ('22', 'GRADUAÇÃO - LETRAS - LÍNGUA PORTUGUESA'), ('23', 'GRADUAÇÃO - MATEMÁTICA'), ('24', 'GRADUAÇÃO - AGRONEGÓCIO'), ('25', 'GRADUAÇÃO - CONSTRUÇÃO DE EDIFÍCIOS'), ('26', 'GRADUAÇÃO - GESTÃO DE TURISMO'), ('27', 'GRADUAÇÃO - GESTÃO PÚBLICA'), ('28', 'GRADUAÇÃO - SISTEMAS ELÉTRICOS'), ('29', 'GRADUAÇÃO - SISTEMAS PARA INTERNET')], default=None, max_length=50, verbose_name='curso')),
                ('sem_mod_ano', models.CharField(default=None, max_length=10, verbose_name='Semestre/Módulo/Ano')),
                ('matricula', models.CharField(default=None, max_length=15, verbose_name='matrícula')),
                ('campus', models.CharField(default='PALMAS', max_length=30, verbose_name='campus')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
            },
            bases=('core.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
    ]
