# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-08 04:23
from __future__ import unicode_literals

from django.db import migrations


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            nome=src.nome,
            cpf=src.cpf,
            email=src.email,
            fone=src.fone,
            endereco=src.endereco,
            num_casa=src.num_casa,
            cep=src.cep,
            bairro=src.bairro,
            cidade=src.cidade,
            estado=src.estado,
            sexo=src.sexo,
            curso=src.curso,
            sem_mod_ano=src.sem_mod_ano,
            matricula=src.matricula,
            campus=src.campus
        )
        dst.save()


def forward_quest_to_aluno_mti(apps, schema_editor):
    """"
    para cada questionario, instanciar um mti com os atributos
    salvar o mti
    associar os alunos do questionario com os alunos mti
    """
    copy_src_to_dst(
        apps.get_model('questionarios', 'QuestionarioOld'),
        apps.get_model('core', 'Aluno')
    )


def backward_quest_to_aluno_mti(apps, schema_editor):
    """"
    para cada questionario, instanciar um mti com os atributos
    salvar o mti
    associar os alunos do questionario com os alunos mti
    """
    copy_src_to_dst(
        apps.get_model('core', 'Aluno'),
        apps.get_model('questionarios', 'QuestionarioOld'),
    )


class Migration(migrations.Migration):


    dependencies = [
        ('core', '0001_initial'),
        ('questionarios', '0033_questionario')
    ]

    operations = [
        # Aqui passa o código pra evoluir a aplicação ou reverter
        migrations.RunPython(forward_quest_to_aluno_mti,
                             backward_quest_to_aluno_mti)
    ]
