# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quest_to_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[(b'1', b'PROEJA - ATENDIMENTO'), (b'2', b'PROEJA - MANUTEN\xc3\x87\xc3\x83O E OPERA\xc3\x87\xc3\x83O DE MICROCOMPUTADORESs'), (b'3', b'TEC. INT. - T\xc3\x89CNICO EM ADMINISTRA\xc3\x87\xc3\x83O'), (b'4', b'TEC. INT. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'5', b'TEC. INT. - T\xc3\x89CNICO EM AGRONEG\xc3\x93CIO'), (b'6', b'TEC. INT. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL '), (b'7', b'TEC. INT. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'8', b'TEC. INT. - T\xc3\x89CNICO EM EVENTOS'), (b'9', b'TEC. INT. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA PARA INTERNET'), (b'10', b'TEC. INT. - T\xc3\x89CNICO EM MECATR\xc3\x94NICA'), (b'11', b'TEC. SUB. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'12', b'TEC. SUB. - T\xc3\x89CNICO EM AUTOMA\xc3\x87\xc3\x83O INDUSTRIAL'), (b'30', b'TEC. SUB. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL'), (b'13', b'TEC. SUB. - T\xc3\x89CNICO EM EDIFICA\xc3\x87\xc3\x95ES'), (b'14', b'TEC. SUB. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'15', b'TEC. SUB. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA'), (b'16', b'TEC. SUB. - T\xc3\x89CNICO EM SECRETARIADO'), (b'17', b'TEC. SUB. - T\xc3\x89CNICO EM SEGURAN\xc3\x87A DO TRABALHO'), (b'18', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA CIVIL'), (b'19', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA EL\xc3\x89TRICA'), (b'20', b'GRADUA\xc3\x87\xc3\x83O - EDUCA\xc3\x87\xc3\x83O F\xc3\x8dSICA'), (b'21', b'GRADUA\xc3\x87\xc3\x83O - F\xc3\x8dSICA'), (b'22', b'GRADUA\xc3\x87\xc3\x83O - LETRAS - L\xc3\x8dNGUA PORTUGUESA'), (b'23', b'GRADUA\xc3\x87\xc3\x83O - MATEM\xc3\x81TICA'), (b'24', b'GRADUA\xc3\x87\xc3\x83O - AGRONEG\xc3\x93CIO'), (b'25', b'GRADUA\xc3\x87\xc3\x83O - CONSTRU\xc3\x87\xc3\x83O DE EDIF\xc3\x8dCIOS'), (b'26', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O DE TURISMO'), (b'27', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O P\xc3\x9aBLICA'), (b'28', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS EL\xc3\x89TRICOS'), (b'29', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS PARA INTERNET')], default=None, max_length=50, verbose_name=b'curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(default=None, max_length=15, verbose_name=b'matr\xc3\xadcula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sem_mod_ano',
            field=models.CharField(default=None, max_length=10, verbose_name=b'Semestre/M\xc3\xb3dulo/Ano'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default=None, max_length=100, verbose_name=b'endere\xc3\xa7o'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='num_casa',
            field=models.CharField(default=0, max_length=4, verbose_name=b'n\xc3\xbamero da casa'),
        ),
    ]
