# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_auto_20180516_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrevista',
            options={'verbose_name': 'Entrevista', 'verbose_name_plural': 'Entrevistas'},
        ),
    ]
