# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0002_auto_20180516_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='cl_1',
            field=models.BooleanField(default=False, verbose_name='C\xf3pia Leg\xed vel do RG e CPF do candidato'),
        ),
        migrations.AlterField(
            model_name='entrevista',
            name='cl_2',
            field=models.BooleanField(default=False, verbose_name='C\xf3pia Leg\xed vel do RG e CPF do respons\xe1vel legal (caso o candidato seja menor de idade)'),
        ),
    ]
