# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrevista', '0004_auto_20190131_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevista',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionarios.QuestionarioOld', unique=True),
        ),
    ]
