# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_auto_20180217_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='condicao_moradia',
            field=models.CharField(choices=[('1', 'Herança'), ('2', 'Própria da família (quitada)'), ('3', 'Própria da família (adquirida por meio de projeto social de habitação, com pagamento de parcelas)'), ('4', 'Própria da família (financiada)'), ('5', 'Cedida (gratuita)'), ('6', 'Própria da família (adquirida por meio de projeto social de habitação, quitada)'), ('7', 'Alugada'), ('8', 'Com terceiros (sem contribuição)'), ('9', 'Com terceiros (com contribuição)'), ('10', 'Ocupação')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='problemas_bairro',
            field=models.CharField(choices=[('1', 'Abastecimento de água'), ('2', 'Alagamentos'), ('3', 'Pavimentação (asfalto nas ruas)'), ('4', 'Energia e iluminação pública'), ('5', 'Ruas esburacadas (erosão)'), ('6', 'Saneamento básico (esgoto)'), ('7', 'Serviços de segurança'), ('8', 'Acessibilidade '), ('9', 'Áreas de recreaçao e lazer'), ('10', 'Limpeza e coleta de lixo'), ('11', 'Serviços de saúde'), ('12', 'Transporte público')], max_length=2, null=True),
        ),
    ]
