# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 13:42
from __future__ import unicode_literals

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0003_auto_20180214_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='id',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
