# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0006_auto_20180219_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='condicao_moradia',
            field=models.CharField(choices=[('1', 'Herança'), ('2', 'Própria da família (quitada)'), ('3', 'Própria da família (adquirida por meio de projeto social de habitação, com pagamento de parcelas)'), ('4', 'Própria da família (financiada)'), ('5', 'Cedida (gratuita)'), ('6', 'Própria da família (adquirida por meio de projeto social de habitação, quitada)'), ('7', 'Alugada'), ('8', 'Com terceiros (sem contribuição)'), ('9', 'Com terceiros (com contribuição)'), ('10', 'Ocupação')], max_length=2),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='condicao_responsavel_casa',
            field=models.CharField(choices=[('1', 'Servidor Público'), ('2', 'Trabalhador contribuinte'), ('3', 'Trabalhador empregado (CLT)'), ('4', 'Trabalhador informal (s/ contrib)'), ('5', 'Desempregado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='dependentes_RBD',
            field=models.IntegerField(verbose_name='Dependentes da Renda Bruta Domiciliar'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_fcarro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Parcela Carro'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_fmoto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Parcela Moto'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_terreno',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Parcela Terreno'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_agua',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Água e esgoto'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Alimentação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_eletrica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Energia elétrica'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_basico',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ensino Fundamental'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_capacitacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cursos de Capacitação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_cursinho',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cursinhos'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Material escolar'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_superior',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_cuidador',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Cuidador de idoso/criança'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_medicamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_plano',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Plano de saúde'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_tratamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tratamento de Saúde'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_transporte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Transporte'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='forma_descarte_lixo',
            field=models.CharField(choices=[('1', 'Serviço público de limpeza'), ('3', 'Jogado em terreno baldio ou em via pública'), ('2', 'Enterrado'), ('4', 'Queimado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='instituicao_anterior',
            field=models.CharField(choices=[('1', 'Particular'), ('2', 'Bolsa total (mérito)'), ('3', 'Bolsa parcial (mérito)'), ('4', 'Bolsa parcial (vulnerabilidade)'), ('5', 'Bolsa total (vulnerabilidade)'), ('6', 'Pública')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='local_moradia',
            field=models.CharField(choices=[('1', 'Zona Urbana'), ('2', 'Zona Rural (fazenda, chácara, sítio)'), ('3', 'Zona Rural (indígena, quilombola, assentamento)'), ('4', 'Área de risco (inundação, deslizamento, ocupação, etc)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='meio_acesso_campus',
            field=models.CharField(choices=[('1', 'Próprio (carro)'), ('2', 'Próprio (moto)'), ('3', 'Carona (sem contribuição)'), ('4', 'Coletivo público (não paga passagem)'), ('5', 'Vai a pé'), ('6', 'Vai de bicicleta'), ('7', 'Carona (com contribuição)'), ('8', 'Coletivo público (paga passagem)'), ('9', 'Alternativo (van, etc)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='origem_renda',
            field=models.IntegerField(verbose_name='Quantidade de pessoas que possuem renda'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='percepcao_seguranca_bairro',
            field=models.CharField(choices=[('1', 'Não oferece risco de segurança aos seus moradores'), ('4', 'É considerado perigoso e os moradores sofrem  com a criminalidade'), ('2', 'Os moradores se sentem seguros (há policiamento nas ruas)'), ('5', 'Frequentemente os moradores sofrem  algum tipo de violência no bairro ou nos arredores'), ('3', 'Não há registro de violência sofrida pelo moradores do bairro')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='problemas_bairro',
            field=models.CharField(choices=[('1', 'Abastecimento de água'), ('2', 'Alagamentos'), ('3', 'Pavimentação (asfalto nas ruas)'), ('4', 'Energia e iluminação pública'), ('5', 'Ruas esburacadas (erosão)'), ('6', 'Saneamento básico (esgoto)'), ('7', 'Serviços de segurança'), ('8', 'Acessibilidade '), ('9', 'Áreas de recreaçao e lazer'), ('10', 'Limpeza e coleta de lixo'), ('11', 'Serviços de saúde'), ('12', 'Transporte público')], max_length=2),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='relacao_financeira',
            field=models.CharField(choices=[(1, 'É independente financeiramente'), (2, 'É independente financeiramente e responsável por parte das despesas domésticas'), (3, 'É independente totalmente e responsável por todas as despesas domésticas'), (4, 'Dependente inteiramente da renda dos pais ou companheiro(s)'), (5, 'Dependente inteiramente da renda de outros parentes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='renda_bruta_domiciliar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='responsavel_domicilio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='servicos_indisponiveis_bairro',
            field=models.CharField(choices=[('1', 'Táxi'), ('2', 'Moto táxi'), ('3', 'Transporte escolar pago'), ('4', 'Ônibus escolar'), ('5', 'Transporte escolar público'), ('6', 'Ônibus coletivo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='total_comodos_casa',
            field=models.CharField(choices=[('1', 'Acima de 9 cômodos'), ('2', 'De 6 a 8 cômodos'), ('3', 'De 3 a 5 cômodos'), ('4', 'De 1 a 2 cômodos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='total_km_casa_campus',
            field=models.CharField(choices=[('1', '5 km (até)'), ('2', '6 a 10 km'), ('3', '11 a 25 km'), ('4', '26 km (acima de)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='total_pessoas_casa',
            field=models.CharField(choices=[('1', 'De 1 a 2 pessoas'), ('2', 'De 3 a 5 pessoas'), ('3', 'De 6 a 8 pessoas'), ('4', 'Acima de 9 pessoas')], max_length=1),
        ),
    ]
