# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0006_auto_20180214_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='id',
            new_name='quest_id',
        ),
    ]
