# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0007_auto_20180215_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='quest_id',
            new_name='id',
        ),
    ]
