# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0008_auto_20180215_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='hashId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
