# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0010_auto_20180219_1412'),
        ('questionarios', '0006_auto_20180219_0024'),
    ]

    operations = [
    ]
