# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0012_auto_20180220_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='relacao_financeira',
            field=models.CharField(choices=[('1', 'É independente financeiramente'), ('2', 'É independente financeiramente e responsável por parte das despesas domésticas'), ('3', 'É independente totalmente e responsável por todas as despesas domésticas'), ('4', 'Dependente inteiramente da renda dos pais ou companheiro(s)'), ('5', 'Dependente inteiramente da renda de outros parentes')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='renda_per_capita',
            field=models.CharField(choices=[('1', '1.405,51 (a partir)'), ('2', '937,01 a 1405,50'), ('3', '468,50 a 937,00'), ('4', '234,25 até 468,49'), ('5', 'de 0 até 234, 24')], default=None, max_length=1, verbose_name='Faixa de renda'),
        ),
    ]
