# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0014_auto_20180220_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='problemas_bairro',
            field=models.CharField(blank=True, choices=[('1', 'Abastecimento de água'), ('2', 'Alagamentos'), ('3', 'Pavimentação (asfalto nas ruas)'), ('4', 'Energia e iluminação pública'), ('5', 'Ruas esburacadas (erosão)'), ('6', 'Saneamento básico (esgoto)'), ('7', 'Serviços de segurança'), ('8', 'Acessibilidade '), ('9', 'Áreas de recreaçao e lazer'), ('10', 'Limpeza e coleta de lixo'), ('11', 'Serviços de saúde'), ('12', 'Transporte público')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='servicos_indisponiveis_bairro',
            field=models.CharField(blank=True, choices=[('1', 'Táxi'), ('2', 'Moto táxi'), ('3', 'Transporte escolar pago'), ('4', 'Ônibus escolar'), ('5', 'Transporte escolar público'), ('6', 'Ônibus coletivo')], max_length=30),
        ),
    ]
