# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0017_auto_20180220_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='problemas_bairro',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='servicos_indisponiveis_bairro',
        ),
    ]
