# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0018_auto_20180220_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='campus',
            field=models.CharField(default='PALMAS', max_length=30, verbose_name='campus'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='cep',
            field=models.CharField(default=None, max_length=9, verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='curso',
            field=models.CharField(choices=[('1', 'PROEJA - ATENDIMENTO'), ('2', 'PROEJA - MANUTENÇÃO E OPERAÇÃO DE MICROCOMPUTADORESs'), ('3', 'TEC. INT. - TÉCNICO EM ADMINISTRAÇÃO'), ('4', 'TEC. INT. - TÉCNICO EM AGRIMENSURA'), ('5', 'TEC. INT. - TÉCNICO EM AGRONEGÓCIO'), ('6', 'TEC. INT. - TÉCNICO EM CONTROLE AMBIENTAL '), ('7', 'TEC. INT. - TÉCNICO EM ELETROTÉCNICA'), ('8', 'TEC. INT. - TÉCNICO EM EVENTOS'), ('9', 'TEC. INT. - TÉCNICO EM INFORMÁTICA PARA INTERNET'), ('10', 'TEC. INT. - TÉCNICO EM MECATRÔNICA'), ('11', 'TEC. SUB. - TÉCNICO EM AGRIMENSURA'), ('12', 'TEC. SUB. - TÉCNICO EM AUTOMAÇÃO INDUSTRIAL'), ('13', 'TEC. SUB. - TÉCNICO EM EDIFICAÇÕES'), ('14', 'TEC. SUB. - TÉCNICO EM ELETROTÉCNICA'), ('15', 'TEC. SUB. - TÉCNICO EM INFORMÁTICA'), ('16', 'TEC. SUB. - TÉCNICO EM SECRETARIADO'), ('17', 'TEC. SUB. - TÉCNICO EM SEGURANÇA DO TRABALHO'), ('18', 'GRADUAÇÃO - ENGENHARIA CIVIL'), ('19', 'GRADUAÇÃO - ENGENHARIA ELÉTRICA'), ('20', 'GRADUAÇÃO - EDUCAÇÃO FÍSICA'), ('21', 'GRADUAÇÃO - FÍSICA'), ('22', 'GRADUAÇÃO - LETRAS - LÍNGUA PORTUGUESA'), ('23', 'GRADUAÇÃO - MATEMÁTICA'), ('24', 'GRADUAÇÃO - AGRONEGÓCIO'), ('25', 'GRADUAÇÃO - CONSTRUÇÃO DE EDIFÍCIOS'), ('26', 'GRADUAÇÃO - GESTÃO DE TURISMO'), ('27', 'GRADUAÇÃO - GESTÃO PÚBLICA'), ('28', 'GRADUAÇÃO - SISTEMAS ELÉTRICOS'), ('29', 'GRADUAÇÃO - SISTEMAS PARA INTERNET')], default=None, max_length=50, verbose_name='curso'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='endereco',
            field=models.CharField(default=None, max_length=100, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='estado',
            field=models.CharField(default='TO', max_length=2, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='fone',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='matricula',
            field=models.CharField(default=None, max_length=15, verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='num_casa',
            field=models.CharField(default=0, max_length=4, verbose_name='número da casa'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='sem_mod_ano',
            field=models.CharField(default=None, max_length=10, verbose_name='Semestre/Módulo/Ano'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='renda_per_capita',
            field=models.CharField(choices=[('1', '1.431,01 (a partir)'), ('2', '954,01 a 1431,00'), ('3', '477,01 a 954,00'), ('4', '238,50 até 477,00'), ('5', 'de 0 até 238, 49')], default=None, max_length=1, verbose_name='Faixa de renda'),
        ),
    ]
