# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-20 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0020_auto_20180220_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionario',
            old_name='end',
            new_name='endereco',
        ),
    ]
