# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0022_auto_20180220_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_fcarro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Parcela Carro'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_fmoto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Parcela Moto'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_bens_terreno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Parcela Terreno'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_agua',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Água e esgoto'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Alimentação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_domesticas_eletrica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Energia elétrica'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_basico',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Ensino Fundamental'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_capacitacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cursos de Capacitação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_cursinho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cursinhos'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_material',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Material escolar'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_educacao_superior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_moradia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Moradia'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_cuidador',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Cuidador de idoso/criança'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_medicamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Medicamentos'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_plano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Plano de saúde'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_saude_tratamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tratamento de Saúde'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='despesas_transporte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Transporte'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='renda_bruta_domiciliar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
