# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import sare.questionarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0023_auto_20180220_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='cpf',
            field=models.CharField(max_length=11, validators=[sare.questionarios.validators.cpf_is_digits, sare.questionarios.validators.cpf_has_correct_length, sare.questionarios.validators.cpf_is_valid, sare.questionarios.validators.format_cpf], verbose_name='CPF'),
        ),
    ]
