# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import sare.questionarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0024_auto_20180222_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='cpf',
            field=models.CharField(max_length=11, validators=[sare.questionarios.validators.cpf_is_digits], verbose_name='CPF'),
        ),
        migrations.AlterUniqueTogether(
            name='questionario',
            unique_together=set([('cpf',)]),
        ),
    ]
