# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import sare.questionarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0025_auto_20180222_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='cpf',
            field=models.CharField(max_length=14, validators=[sare.questionarios.validators.cpf_is_digits, sare.questionarios.validators.format_cpf, sare.questionarios.validators.cpf_is_valid], verbose_name='CPF'),
        ),
    ]
