# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import sare.questionarios.validators


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0028_auto_20180226_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='cpf',
            field=models.CharField(max_length=14, validators=[sare.questionarios.validators.cpf_is_digits, sare.questionarios.validators.format_cpf], verbose_name='CPF'),
        ),
    ]
