# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0031_auto_20180301_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionario',
            unique_together=set([]),
        ),
    ]
