# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-12 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0031_auto_20180301_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questionario',
            new_name='QuestionarioOld',
        ),
    ]
