# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180405_1547'),
        ('questionarios', '0032_auto_20180405_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='aluno',
        ),
        migrations.AddField(
            model_name='questionario',
            name='aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
    ]
