# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0034_quest_to_dimensao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensaoambiental',
            options={'verbose_name_plural': 'Dimens\xe3o Ambiental'},
        ),
        migrations.AlterModelOptions(
            name='dimensaocultural',
            options={'verbose_name_plural': 'Dimens\xe3o Cultural'},
        ),
        migrations.AlterModelOptions(
            name='dimensaoeconomica',
            options={'verbose_name': 'dimens\xe3o econ\xf4mica', 'verbose_name_plural': 'dimens\xe3o econ\xf4mica'},
        ),
        migrations.AlterModelOptions(
            name='dimensaosocial',
            options={'verbose_name_plural': 'Dimens\xe3o Social'},
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='ambiental',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='cultural',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='economica',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='social',
        ),
        migrations.AlterField(
            model_name='dimensaoambiental',
            name='forma_descarte_lixo',
            field=models.CharField(choices=[(b'1', b'Servi\xc3\xa7o p\xc3\xbablico de limpeza'), (b'3', b'Jogado em terreno baldio ou em via p\xc3\xbablica'), (b'2', b'Enterrado'), (b'4', b'Queimado')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaoambiental',
            name='percepcao_seguranca_bairro',
            field=models.CharField(choices=[(b'1', b'N\xc3\xa3o oferece risco de seguran\xc3\xa7a aos seus moradores'), (b'4', b'\xc3\x89 considerado perigoso e os moradores sofrem  com a criminalidade'), (b'2', b'Os moradores se sentem seguros (h\xc3\xa1 policiamento nas ruas)'), (b'5', b'Frequentemente os moradores sofrem  algum tipo de viol\xc3\xaancia no bairro ou nos arredores'), (b'3', b'N\xc3\xa3o h\xc3\xa1 registro de viol\xc3\xaancia sofrida pelo moradores do bairro')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='cor_raca',
            field=models.CharField(choices=[(b'1', b'Branca'), (b'2', b'Amarela'), (b'3', b'Parda'), (b'4', b'Estrangeiro'), (b'5', b'Preta'), (b'6', b'Afro descendente Quilombola'), (b'7', b'Ind\xc3\xadgena'), (b'8', b'Estrangeiro refugiado')], default=None, max_length=1, verbose_name=b'Como voc\xc3\xaa considera sua cor/ra\xc3\xa7a?'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_cultural',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Cultural'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_economico',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Econ\xc3\xb4mico'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_estetico',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Est\xc3\xa9tico'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_genero',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'G\xc3\xaanero'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_mental',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Mental'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_orientacao_sexual',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Orienta\xc3\xa7\xc3\xa3o sexual'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_racial',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Racial'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='preconceito_religioso',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Religioso'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_abandono',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Neglig\xc3\xaancia / abandono familiar'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_abuso_familiar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Abuso por parte de familiares ou pessoas conhecidas'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_assedio_moral',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Ass\xc3\xa9dio Moral'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_atentado_pudor',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Atentado ao pudor'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_cyberbulling',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Cyberbulling (por meio de redes sociais)'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_fisica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'F\xc3\xadsica'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_patrimonial',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Patrimonial/financeira'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_psicologica_moral',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Psicol\xc3\xb3gica / moral'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_religiosa',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Religiosa'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_sexual',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sexual'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_trafico_humano',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tr\xc3\xa1fico de seres humanos'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_urbana',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Viol\xc3\xaancia urbana(assalto, transito, etc)'),
        ),
        migrations.AlterField(
            model_name='dimensaocultural',
            name='violencia_verbal',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Verbal(xingamentos, desacatos, etc.)'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_domesticas_agua',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'\xc3\x81gua e esgoto'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_domesticas_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Alimenta\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_domesticas_eletrica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Energia el\xc3\xa9trica'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_educacao_capacitacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Cursos de Capacita\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_educacao_superior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Gradua\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_saude_cuidador',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Cuidador de idoso/crian\xc3\xa7a'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_saude_plano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Plano de sa\xc3\xbade'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='despesas_saude_tratamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Tratamento de Sa\xc3\xbade'),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='relacao_financeira',
            field=models.CharField(choices=[(b'1', b'\xc3\x89 independente financeiramente'), (b'2', b'\xc3\x89 independente financeiramente e respons\xc3\xa1vel por parte das despesas dom\xc3\xa9sticas'), (b'3', b'\xc3\x89 independente totalmente e respons\xc3\xa1vel por todas as despesas dom\xc3\xa9sticas'), (b'4', b'Dependente inteiramente da renda dos pais ou companheiro(s)'), (b'5', b'Dependente inteiramente da renda de outros parentes')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaoeconomica',
            name='renda_per_capita',
            field=models.CharField(choices=[(b'1', b'1.431,01 (a partir)'), (b'2', b'954,01 a 1431,00'), (b'3', b'477,01 a 954,00'), (b'4', b'238,50 at\xc3\xa9 477,00'), (b'5', b'de 0 at\xc3\xa9 238, 49')], default=None, max_length=1, verbose_name=b'Faixa de renda'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='condicao_moradia',
            field=models.CharField(choices=[(b'1', b'Heran\xc3\xa7a'), (b'2', b'Pr\xc3\xb3pria da fam\xc3\xadlia (quitada)'), (b'3', b'Pr\xc3\xb3pria da fam\xc3\xadlia (adquirida por meio de projeto social de habita\xc3\xa7\xc3\xa3o, com pagamento de parcelas)'), (b'4', b'Pr\xc3\xb3pria da fam\xc3\xadlia (financiada)'), (b'5', b'Cedida (gratuita)'), (b'6', b'Pr\xc3\xb3pria da fam\xc3\xadlia (adquirida por meio de projeto social de habita\xc3\xa7\xc3\xa3o, quitada)'), (b'7', b'Alugada'), (b'8', b'Com terceiros (sem contribui\xc3\xa7\xc3\xa3o)'), (b'9', b'Com terceiros (com contribui\xc3\xa7\xc3\xa3o)'), (b'10', b'Ocupa\xc3\xa7\xc3\xa3o')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='condicao_responsavel_casa',
            field=models.CharField(choices=[(b'1', b'Servidor P\xc3\xbablico'), (b'2', b'Trabalhador contribuinte'), (b'3', b'Trabalhador empregado (CLT)'), (b'4', b'Trabalhador informal (s/ contrib)'), (b'5', b'Desempregado')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='instituicao_anterior',
            field=models.CharField(choices=[(b'1', b'Particular'), (b'2', b'Bolsa total (m\xc3\xa9rito)'), (b'3', b'Bolsa parcial (m\xc3\xa9rito)'), (b'4', b'Bolsa parcial (vulnerabilidade)'), (b'5', b'Bolsa total (vulnerabilidade)'), (b'6', b'P\xc3\xbablica')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='local_moradia',
            field=models.CharField(choices=[(b'1', b'Zona Urbana'), (b'2', b'Zona Rural (fazenda, ch\xc3\xa1cara, s\xc3\xadtio)'), (b'3', b'Zona Rural (ind\xc3\xadgena, quilombola, assentamento)'), (b'4', b'\xc3\x81rea de risco (inunda\xc3\xa7\xc3\xa3o, deslizamento, ocupa\xc3\xa7\xc3\xa3o, etc)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='meio_acesso_campus',
            field=models.CharField(choices=[(b'1', b'Pr\xc3\xb3prio (carro)'), (b'2', b'Pr\xc3\xb3prio (moto)'), (b'3', b'Carona (sem contribui\xc3\xa7\xc3\xa3o)'), (b'4', b'Coletivo p\xc3\xbablico (n\xc3\xa3o paga passagem)'), (b'5', b'Vai a p\xc3\xa9'), (b'6', b'Vai de bicicleta'), (b'7', b'Carona (com contribui\xc3\xa7\xc3\xa3o)'), (b'8', b'Coletivo p\xc3\xbablico (paga passagem)'), (b'9', b'Alternativo (van, etc)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='pne_def_fisica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui defici\xc3\xaancia f\xc3\xadsica?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='pne_def_mental_grave',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia mental grave?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='pne_def_mental_leve',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia mental leve?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='pne_parcial_visao_audicao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia parcial de vis\xc3\xa3o/audi\xc3\xa7\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='pne_total_visao_audicao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia total  de vis\xc3\xa3o/audi\xc3\xa7\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='psico_conflito_familiar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Vivencia algum problema/conflito familiar'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='psico_depressao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sofre de depress\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='psico_dificuldade_concentrar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sente dificuldade em se concentrar?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='saude_bebida_drogas',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Faz uso, abuso de bebida alc\xc3\xb3olica e/ou drogas?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='saude_doenca_cronica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui doen\xc3\xa7a cr\xc3\xb4nica?'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='saude_doenca_grave',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui doen\xc3\xa7a grave'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='saude_medicamento_diario',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Faz uso de medicamento di\xc3\xa1rio, de impacto na renda familiar'),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='total_comodos_casa',
            field=models.CharField(choices=[(b'1', b'Acima de 9 c\xc3\xb4modos'), (b'2', b'De 6 a 8 c\xc3\xb4modos'), (b'3', b'De 3 a 5 c\xc3\xb4modos'), (b'4', b'De 1 a 2 c\xc3\xb4modos')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='dimensaosocial',
            name='total_km_casa_campus',
            field=models.CharField(choices=[(b'1', b'5 km (at\xc3\xa9)'), (b'2', b'6 a 10 km'), (b'3', b'11 a 25 km'), (b'4', b'26 km (acima de)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='fale_mais_familia',
            field=models.CharField(max_length=500, verbose_name=b'Fale mais sobre sua fam\xc3\xadlia'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='condicao_moradia',
            field=models.CharField(choices=[(b'1', b'Heran\xc3\xa7a'), (b'2', b'Pr\xc3\xb3pria da fam\xc3\xadlia (quitada)'), (b'3', b'Pr\xc3\xb3pria da fam\xc3\xadlia (adquirida por meio de projeto social de habita\xc3\xa7\xc3\xa3o, com pagamento de parcelas)'), (b'4', b'Pr\xc3\xb3pria da fam\xc3\xadlia (financiada)'), (b'5', b'Cedida (gratuita)'), (b'6', b'Pr\xc3\xb3pria da fam\xc3\xadlia (adquirida por meio de projeto social de habita\xc3\xa7\xc3\xa3o, quitada)'), (b'7', b'Alugada'), (b'8', b'Com terceiros (sem contribui\xc3\xa7\xc3\xa3o)'), (b'9', b'Com terceiros (com contribui\xc3\xa7\xc3\xa3o)'), (b'10', b'Ocupa\xc3\xa7\xc3\xa3o')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='condicao_responsavel_casa',
            field=models.CharField(choices=[(b'1', b'Servidor P\xc3\xbablico'), (b'2', b'Trabalhador contribuinte'), (b'3', b'Trabalhador empregado (CLT)'), (b'4', b'Trabalhador informal (s/ contrib)'), (b'5', b'Desempregado')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='cor_raca',
            field=models.CharField(choices=[(b'1', b'Branca'), (b'2', b'Amarela'), (b'3', b'Parda'), (b'4', b'Estrangeiro'), (b'5', b'Preta'), (b'6', b'Afro descendente Quilombola'), (b'7', b'Ind\xc3\xadgena'), (b'8', b'Estrangeiro refugiado')], default=None, max_length=1, verbose_name=b'Como voc\xc3\xaa considera sua cor/ra\xc3\xa7a?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='curso',
            field=models.CharField(choices=[(b'1', b'PROEJA - ATENDIMENTO'), (b'2', b'PROEJA - MANUTEN\xc3\x87\xc3\x83O E OPERA\xc3\x87\xc3\x83O DE MICROCOMPUTADORESs'), (b'3', b'TEC. INT. - T\xc3\x89CNICO EM ADMINISTRA\xc3\x87\xc3\x83O'), (b'4', b'TEC. INT. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'5', b'TEC. INT. - T\xc3\x89CNICO EM AGRONEG\xc3\x93CIO'), (b'6', b'TEC. INT. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL '), (b'7', b'TEC. INT. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'8', b'TEC. INT. - T\xc3\x89CNICO EM EVENTOS'), (b'9', b'TEC. INT. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA PARA INTERNET'), (b'10', b'TEC. INT. - T\xc3\x89CNICO EM MECATR\xc3\x94NICA'), (b'11', b'TEC. SUB. - T\xc3\x89CNICO EM AGRIMENSURA'), (b'12', b'TEC. SUB. - T\xc3\x89CNICO EM AUTOMA\xc3\x87\xc3\x83O INDUSTRIAL'), (b'30', b'TEC. SUB. - T\xc3\x89CNICO EM CONTROLE AMBIENTAL'), (b'13', b'TEC. SUB. - T\xc3\x89CNICO EM EDIFICA\xc3\x87\xc3\x95ES'), (b'14', b'TEC. SUB. - T\xc3\x89CNICO EM ELETROT\xc3\x89CNICA'), (b'15', b'TEC. SUB. - T\xc3\x89CNICO EM INFORM\xc3\x81TICA'), (b'16', b'TEC. SUB. - T\xc3\x89CNICO EM SECRETARIADO'), (b'17', b'TEC. SUB. - T\xc3\x89CNICO EM SEGURAN\xc3\x87A DO TRABALHO'), (b'18', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA CIVIL'), (b'19', b'GRADUA\xc3\x87\xc3\x83O - ENGENHARIA EL\xc3\x89TRICA'), (b'20', b'GRADUA\xc3\x87\xc3\x83O - EDUCA\xc3\x87\xc3\x83O F\xc3\x8dSICA'), (b'21', b'GRADUA\xc3\x87\xc3\x83O - F\xc3\x8dSICA'), (b'22', b'GRADUA\xc3\x87\xc3\x83O - LETRAS - L\xc3\x8dNGUA PORTUGUESA'), (b'23', b'GRADUA\xc3\x87\xc3\x83O - MATEM\xc3\x81TICA'), (b'24', b'GRADUA\xc3\x87\xc3\x83O - AGRONEG\xc3\x93CIO'), (b'25', b'GRADUA\xc3\x87\xc3\x83O - CONSTRU\xc3\x87\xc3\x83O DE EDIF\xc3\x8dCIOS'), (b'26', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O DE TURISMO'), (b'27', b'GRADUA\xc3\x87\xc3\x83O - GEST\xc3\x83O P\xc3\x9aBLICA'), (b'28', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS EL\xc3\x89TRICOS'), (b'29', b'GRADUA\xc3\x87\xc3\x83O - SISTEMAS PARA INTERNET')], default=None, max_length=50, verbose_name=b'curso'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_domesticas_agua',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'\xc3\x81gua e esgoto'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_domesticas_alimentacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Alimenta\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_domesticas_eletrica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Energia el\xc3\xa9trica'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_educacao_capacitacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Cursos de Capacita\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_educacao_superior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Gradua\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_saude_cuidador',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Cuidador de idoso/crian\xc3\xa7a'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_saude_plano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Plano de sa\xc3\xbade'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='despesas_saude_tratamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name=b'Tratamento de Sa\xc3\xbade'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='endereco',
            field=models.CharField(default=None, max_length=100, verbose_name=b'endere\xc3\xa7o'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='fale_mais_familia',
            field=models.CharField(max_length=500, verbose_name=b'Fale mais sobre sua fam\xc3\xadlia'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='forma_descarte_lixo',
            field=models.CharField(choices=[(b'1', b'Servi\xc3\xa7o p\xc3\xbablico de limpeza'), (b'3', b'Jogado em terreno baldio ou em via p\xc3\xbablica'), (b'2', b'Enterrado'), (b'4', b'Queimado')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='instituicao_anterior',
            field=models.CharField(choices=[(b'1', b'Particular'), (b'2', b'Bolsa total (m\xc3\xa9rito)'), (b'3', b'Bolsa parcial (m\xc3\xa9rito)'), (b'4', b'Bolsa parcial (vulnerabilidade)'), (b'5', b'Bolsa total (vulnerabilidade)'), (b'6', b'P\xc3\xbablica')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='local_moradia',
            field=models.CharField(choices=[(b'1', b'Zona Urbana'), (b'2', b'Zona Rural (fazenda, ch\xc3\xa1cara, s\xc3\xadtio)'), (b'3', b'Zona Rural (ind\xc3\xadgena, quilombola, assentamento)'), (b'4', b'\xc3\x81rea de risco (inunda\xc3\xa7\xc3\xa3o, deslizamento, ocupa\xc3\xa7\xc3\xa3o, etc)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='matricula',
            field=models.CharField(default=None, max_length=15, verbose_name=b'matr\xc3\xadcula'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='meio_acesso_campus',
            field=models.CharField(choices=[(b'1', b'Pr\xc3\xb3prio (carro)'), (b'2', b'Pr\xc3\xb3prio (moto)'), (b'3', b'Carona (sem contribui\xc3\xa7\xc3\xa3o)'), (b'4', b'Coletivo p\xc3\xbablico (n\xc3\xa3o paga passagem)'), (b'5', b'Vai a p\xc3\xa9'), (b'6', b'Vai de bicicleta'), (b'7', b'Carona (com contribui\xc3\xa7\xc3\xa3o)'), (b'8', b'Coletivo p\xc3\xbablico (paga passagem)'), (b'9', b'Alternativo (van, etc)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='num_casa',
            field=models.CharField(default=0, max_length=4, verbose_name=b'n\xc3\xbamero da casa'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='percepcao_seguranca_bairro',
            field=models.CharField(choices=[(b'1', b'N\xc3\xa3o oferece risco de seguran\xc3\xa7a aos seus moradores'), (b'4', b'\xc3\x89 considerado perigoso e os moradores sofrem  com a criminalidade'), (b'2', b'Os moradores se sentem seguros (h\xc3\xa1 policiamento nas ruas)'), (b'5', b'Frequentemente os moradores sofrem  algum tipo de viol\xc3\xaancia no bairro ou nos arredores'), (b'3', b'N\xc3\xa3o h\xc3\xa1 registro de viol\xc3\xaancia sofrida pelo moradores do bairro')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='pne_def_fisica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui defici\xc3\xaancia f\xc3\xadsica?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='pne_def_mental_grave',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia mental grave?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='pne_def_mental_leve',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia mental leve?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='pne_parcial_visao_audicao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia parcial de vis\xc3\xa3o/audi\xc3\xa7\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='pne_total_visao_audicao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tem defici\xc3\xaancia total  de vis\xc3\xa3o/audi\xc3\xa7\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_cultural',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Cultural'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_economico',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Econ\xc3\xb4mico'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_estetico',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Est\xc3\xa9tico'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_genero',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'G\xc3\xaanero'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_mental',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Mental'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_orientacao_sexual',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Orienta\xc3\xa7\xc3\xa3o sexual'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_racial',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Racial'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='preconceito_religioso',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Religioso'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='psico_conflito_familiar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Vivencia algum problema/conflito familiar'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='psico_depressao',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sofre de depress\xc3\xa3o?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='psico_dificuldade_concentrar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sente dificuldade em se concentrar?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='relacao_financeira',
            field=models.CharField(choices=[(b'1', b'\xc3\x89 independente financeiramente'), (b'2', b'\xc3\x89 independente financeiramente e respons\xc3\xa1vel por parte das despesas dom\xc3\xa9sticas'), (b'3', b'\xc3\x89 independente totalmente e respons\xc3\xa1vel por todas as despesas dom\xc3\xa9sticas'), (b'4', b'Dependente inteiramente da renda dos pais ou companheiro(s)'), (b'5', b'Dependente inteiramente da renda de outros parentes')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='renda_per_capita',
            field=models.CharField(choices=[(b'1', b'1.431,01 (a partir)'), (b'2', b'954,01 a 1431,00'), (b'3', b'477,01 a 954,00'), (b'4', b'238,50 at\xc3\xa9 477,00'), (b'5', b'de 0 at\xc3\xa9 238, 49')], default=None, max_length=1, verbose_name=b'Faixa de renda'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='saude_bebida_drogas',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Faz uso, abuso de bebida alc\xc3\xb3olica e/ou drogas?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='saude_doenca_cronica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui doen\xc3\xa7a cr\xc3\xb4nica?'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='saude_doenca_grave',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Possui doen\xc3\xa7a grave'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='saude_medicamento_diario',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Faz uso de medicamento di\xc3\xa1rio, de impacto na renda familiar'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='sem_mod_ano',
            field=models.CharField(default=None, max_length=10, verbose_name=b'Semestre/M\xc3\xb3dulo/Ano'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='total_comodos_casa',
            field=models.CharField(choices=[(b'1', b'Acima de 9 c\xc3\xb4modos'), (b'2', b'De 6 a 8 c\xc3\xb4modos'), (b'3', b'De 3 a 5 c\xc3\xb4modos'), (b'4', b'De 1 a 2 c\xc3\xb4modos')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='total_km_casa_campus',
            field=models.CharField(choices=[(b'1', b'5 km (at\xc3\xa9)'), (b'2', b'6 a 10 km'), (b'3', b'11 a 25 km'), (b'4', b'26 km (acima de)')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_abandono',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Neglig\xc3\xaancia / abandono familiar'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_abuso_familiar',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Abuso por parte de familiares ou pessoas conhecidas'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_assedio_moral',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Ass\xc3\xa9dio Moral'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_atentado_pudor',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Atentado ao pudor'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_cyberbulling',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Cyberbulling (por meio de redes sociais)'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_fisica',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'F\xc3\xadsica'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_patrimonial',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Patrimonial/financeira'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_psicologica_moral',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Psicol\xc3\xb3gica / moral'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_religiosa',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Religiosa'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_sexual',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Sexual'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_trafico_humano',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Tr\xc3\xa1fico de seres humanos'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_urbana',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Viol\xc3\xaancia urbana(assalto, transito, etc)'),
        ),
        migrations.AlterField(
            model_name='questionarioold',
            name='violencia_verbal',
            field=models.CharField(choices=[(b'1', b'Voc\xc3\xaa'), (b'2', b'Fam\xc3\xadlia'), (b'3', b'Ambos'), (b'0', b'N\xc3\xa3o se aplica')], default=None, max_length=1, verbose_name=b'Verbal(xingamentos, desacatos, etc.)'),
        ),
    ]
