# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-18 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0034_quest_to_dimensao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dimensaoambiental',
            options={'verbose_name_plural': 'Dimensão Ambiental'},
        ),
        migrations.AlterModelOptions(
            name='dimensaocultural',
            options={'verbose_name_plural': 'Dimensão Cultural'},
        ),
        migrations.AlterModelOptions(
            name='dimensaoeconomica',
            options={'verbose_name': 'dimensão econômica', 'verbose_name_plural': 'dimensão econômica'},
        ),
        migrations.AlterModelOptions(
            name='dimensaosocial',
            options={'verbose_name_plural': 'Dimensão Social'},
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='ambiental',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='cultural',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='economica',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='social',
        ),
    ]
